## **Homework 2**

### Create a copy of the notebook to start answering the questions. Name your notebook in the format HW2_lastname_firstname.ipynb to facilitate the grading process. 

### Answer all the questions, test your code to ensure there are no errors and the results are as expected. Once you have answered all the questions, save the final copy, then go to File-> click on Download.ipynb. Once the local copy has been downloaded, submit your file on Blackboard under the corresponding assignment section. Also provide us a link to your notebook during submission. 

### **The due date of this homework is 02/12/2021 (Friday).**

### Please ensure you follow all the steps mentioned in the homework.

### All the questions have a sample input and output to help you understand the question.

### You can submit your solutions any number of times until the deadline.


**Q1. Lets consider your data is like the below cell:**

**Q1-1**: Write a program that create a dataframe from the data.

**Q1-2:** Select people that are psychologist or teacher and their number of cars is greater than their family size.

**Q1-3:** Select people who have at most 2 family members and at least 1 car.

**Q1-4:** Write a code that get number of unique jobs in this dataset.





In [ ]:
data = {"name": ["Joseph", "Jacob", "Sam", "Jesee", "Ryan", "Lisa", "Lee"],
        "job": ["teacher", "psychologist", "data scientist", "software developer", "psychologist", "psychologist", "teacher"],
        "family_size": [3, 2, 1, 4, 2, 3, 2],
        "num_cars": [3, 1, 1, 2, 2, 4, 1]}

In [ ]:
import numpy as np
import pandas as pd
df = pd.DataFrame(data)
q2 = df[((df["job"]== "psychologist") | (df["job"]== "teacher")) & (df["num_cars"]> df["family_size"])]
q3 = df[(df["family_size"]<= 2) & (df["num_cars"]>= 1)]
q4 = df.job.unique()
print(df)
print(q2)
print(q3)
print(q4)





     name                 job  family_size  num_cars
0  Joseph             teacher            3         3
1   Jacob        psychologist            2         1
2     Sam      data scientist            1         1
3   Jesee  software developer            4         2
4    Ryan        psychologist            2         2
5    Lisa        psychologist            3         4
6     Lee             teacher            2         1
   name           job  family_size  num_cars
5  Lisa  psychologist            3         4
    name             job  family_size  num_cars
1  Jacob    psychologist            2         1
2    Sam  data scientist            1         1
4   Ryan    psychologist            2         2
6    Lee         teacher            2         1
['teacher' 'psychologist' 'data scientist' 'software developer']


**Q2. Lets consider you have two series like the below cell. Compute the mean of weights of each fruit.**

In [ ]:
import numpy as np
fruit = pd.Series(np.random.choice(['apple', 'banana', 'carrot'], 10))
weights = pd.Series(np.linspace(1, 10, 10))

In [ ]:
import pandas as pd
df = pd.DataFrame(fruit)
df["Weight"] = weights
df.columns = ["Fruit", "Weight"]
print(df)
apple = df[(df['Fruit']=="apple")]
banana = df[(df['Fruit']=="banana")]
carrot = df[(df['Fruit']=="carrot")]
apple_mean = float(apple.mean())
banana_mean = float(banana.mean())
carrot_mean = float(carrot.mean())
print('Apple Mean: ' + str(apple_mean))
print('Banana Mean: ' + str(banana_mean))
print('Carrot Mean: ' + str(carrot_mean))



    Fruit  Weight
0  banana     1.0
1  carrot     2.0
2  carrot     3.0
3  carrot     4.0
4  carrot     5.0
5  carrot     6.0
6   apple     7.0
7  banana     8.0
8  banana     9.0
9   apple    10.0
Apple Mean: 8.5
Banana Mean: 6.0
Carrot Mean: 4.0


**Q3. Consider the below course_name array:**

**Q3-1**: Write a NumPy program to get the indices of the sorted elements of **course_name** array.

**Q3-2:** Write numpy code to check whether each element of **course_name** array starts with "P".


In [ ]:
import numpy as np
course_name = np.array(['Python', 'JS', 'examples', 'PHP', 'html'])

In [ ]:
cn_indices = np.argsort(course_name)
print(cn_indices)
bool_start_with_p = []
names_start_with_p = []
for i in course_name:
  e = i.upper()
  if e.startswith("P"):
    start_with_p.append(True)
    names_start_with_p.append(i)
  else:
    start_with_p.append(False)

    
print("Boolean list of corresponding course_name index:", start_with_p)
print("Courses that start with p:", names_start_with_p)



[1 3 0 2 4]
Boolean list of corresponding course_name index: [True, False, False, True, False, True, False, False, True, False, True, False, False, True, False, True, False, False, True, False]
Courses that start with p: ['Python', 'PHP']


**Q4. Consider the below student_id array:**

**Q4-1:** Reverse the **student_id** array. Print both original and reversed array.

**Q4-2:** Get the 3-largest values of **student_id** array.

In [ ]:
import numpy as np
student_id = np.array([1023, 5202, 6230, 1671, 1682, 5241, 4532])

In [ ]:
student_id_flipped = np.flip(student_id)
print(student_id)
print(student_id_flipped)
ascending = np.sort(student_id)
three_largest = ascending[[-1, -2, -3]]
print("Three Largest:", three_largest)


[1023 5202 6230 1671 1682 5241 4532]
[4532 5241 1682 1671 6230 5202 1023]
Three Largest: [6230 5241 5202]


# **Q5: Write a numpy program to print sum of all the multiples of 3 or 5 below 100**

In [ ]:
import numpy as np
range = np.arange(1, 100)
target = range[(range % 3 == 0) | (range % 5 == 0)]
print(target)
print(target.sum())

# Hint: you can use arange to start off

[ 3  5  6  9 10 12 15 18 20 21 24 25 27 30 33 35 36 39 40 42 45 48 50 51
 54 55 57 60 63 65 66 69 70 72 75 78 80 81 84 85 87 90 93 95 96 99]
2318


**Q6. Consider the below array.**

Q6.1. Write a code to swap column 1 with column 2.

Q6.2. Write a code to swap row 0 with row 1.

In [ ]:
import numpy as np

arr = np.arange(12).reshape(3,4)
print(arr)
arr[:, [2,1]] = arr[:,[1,2]]
print("Swap Columns 1 and 2!")
print(arr)
arr = np.arange(12).reshape(3,4)
arr[[1,0], :] = arr[[0,1], :]
print("Swap Rows 0 and 1!")
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Swap Columns 1 and 2!
[[ 0  2  1  3]
 [ 4  6  5  7]
 [ 8 10  9 11]]
Swap Rows 0 and 1!
[[ 4  5  6  7]
 [ 0  1  2  3]
 [ 8  9 10 11]]


In [ ]:
# Type your solution here